### ISSUE TITLE
Add Bspwm, Polybar and Dunst

### ISSUE THREAD

**Issue by TzZek** [SadError256/archkick#2]
Would be nice to see these added. Dunst specifically for notifications on a twm.

Bspwm: https://wiki.archlinux.org/index.php/Bspwm
Polybar: https://aur.archlinux.org/packages/polybar/
Dunst: https://wiki.archlinux.org/index.php/Dunst

**Comment by SadError256** [comment]
SoXX-TheFennec has got a pull request that i merged mentioning your change. Your request has been included!
