### ISSUE TITLE
Suggestion for i3

### ISSUE THREAD

**Issue by SoXX-TheFennec** [SadError256/archkick#3]
It's not really an Issue but a suggestion, I think it would be better to install all i3 programmes:

- i3-gaps (instead of standard i3)
- i3lock (and therefore ImageMagick)
- i3blocks
- i3status

Great works so far, I really like your script :D

**Comment by SadError256** [comment]
@SoXX-TheFennec hello!

I believe the i3 package Includes all three besides i3 gaps. I'll add them just in case they are missed

**Comment by SadError256** [comment]
Request merged, you have been added to the Contributors file. Contact me if you want to be removed
